name: HIL test workflow
on:
    workflow_dispatch:

jobs:
    check_hil_server_integration:
        name: Check HIL server integration
        runs-on: hilserver
        steps:
            - name: Verify ST-Link connection
              run: st-info --probe

            - name: Verify my-micro-hil availability
              run: hiltest -h

            - name: Verify lighttpd availability
              run: lighttpd -v
              
